[input_parameters]
Lx = 50.0
Ly = 50.0
Lz = 1.0
ms = [1.0, 25.0]
qs = [-1.0, 1.0]
alpha_s = [0.25, 0.25, 0.25, 0.05, 0.05, 0.05]
u_s = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Omega_ce = 0.5
nu = 1.0
D = 0.0
t_max = 500.0
ode_tolerance = 1e-7

[solver_parameters]
Nx = 50
Ny = 50
Nz = 1
Nn = 5
Nm = 5
Np = 5
Ns = 2
N_DG=2
dims=2
timesteps = 51
dt = 0.00001
solver = "Dopri8"