# Two-stream instability of two counter-streaming electron beams.
# Run with:  spectrax input_1D_two_stream.toml
[input_parameters]
Lx = 12.57
t_max = 50.0
nu = 3.0
ode_tolerance = 1e-7

[solver_parameters]
Nx = 33
Nn = 50
timesteps = 501

[species.beam_right]
charge = -1
vth = 0.707107
drift = 1.0
perturbation_amplitude = 0.01

[species.beam_left]
charge = -1
vth = 0.707107
drift = -1.0
perturbation_amplitude = 0.01
